version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - setup_remote_docker
      - run: 'docker build -t fischcheng/docker-react -f Dockerfile.dev .'
      - run: 'docker run -e CI=true fischcheng/docker-react npm run test'
