version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 'docker build -t fischcheng/docker-react -f Dockerfile.dev .'
      - run: 'docker run -e CI=true fischcheng/docker-react npm run test'
